### ISSUE TITLE
Erlang 23 HTTPC support - update Hackney to ~> 1.16

### ISSUE THREAD

**Issue by darrenklein** [lau/tzdata#100]
Hello, thank you so much for your hard work on this project.

I just wanted to suggest that the Hackney dependency should probably be updated to at least version 1.16. Erlang version 23 added support for tlsv1.3 and removed support for sslv3, and Hackney 1.16 addresses those changes.

Here are some discussions related to this issue:

https://elixirforum.com/t/erlang-v-23-0-and-httpoison-error/31615
https://stackoverflow.com/questions/62162329/httpoison-request-5-raises-httpoison-error-with-weird-reason

Thanks again!

**Comment by kamilkowalski** [comment]
Hi @darrenklein, I think your issue is now resolved - `tzdata` v1.1.0 depends on `hackney ~> 1.17` :tada:

**Comment by darrenklein** [comment]
Indeed, looks good. Thanks!
