### ISSUE TITLE
Support for 2016.b

### ISSUE THREAD

**Issue by olgeni** [lau/tzdata#17]
Hi, is a release with 2016.b planned? :)

**Comment by lau** [comment]
It supports 2016b already. It should download automatically. If you deploy it on a server or device without internet access you can put a 2016b file on to your server manually.

Do you deploy on a server without internet access?

**Comment by olgeni** [comment]
I have a couple of servers w/o internet access. Should I just drop the IANA files somewhere, or do I build and ets file locally and then copy it?

**Comment by lau** [comment]
If you start tzdata locally with `iex -S mix`and have internet, it will download the newest version and generate a .ets file in the tzdata `priv/releases` dir: `2016b.ets`

You can copy this file to your servers. E.g. to `"/etc/elixir_tzdata_data/releases/2016b.ets"`
Then look at the readme: the section called "Data directory and releases".
You put this config in your app: `config :tzdata, :data_dir, "/etc/elixir_tzdata_data"`

If you have an idea for improving the documentation and/or readme to make this more clear, please make a pull request.

**Comment by lau** [comment]
I just edited my answer slightly.

**Comment by olgeni** [comment]
Got it - we now ship updates with Ansible to hosts w/o internet access. Thanks! :)
