### ISSUE TITLE
ets file is missing and autoupdate :disabled ==> :nxdomain error

### ISSUE THREAD

**Issue by martin-langhoff** [lau/tzdata#25]
Using `v0.5.7`, in a compiled release, I find that tzdata errors out with `:nxdomain` when autoupdate is set to `:disabled` and the ets file is missing.

The error stacktrace (https://files.slack.com/files-pri/T08E7VBSA-F20JFDHT6/pasted_image_at_2016_08_11_03_28_pm.png
) makes me think it is trying to make a network connection (the test VM is "disconnected", and the error says `:nxdomain`).

* Should not connect to the network if `autoupdate = :disabled`
* Should have a better, clearer error msg

**Comment by lau** [comment]
Hi Martin. What do you mean by "the ets file is missing"? An ets file ships with tzdata.

**Comment by martin-langhoff** [comment]
Good question. As it's a release (for installation as an rpm) into tightly controlled systems, we are also defining `data_dir` to point to `/var/lib/myapp`. 

So the ets file gets copied into `apps/myapp/rel/myapp/lib/tzdata-0.x.y/priv/release_ets` during the build/release process. However, at runtime `data_dir` is pointing to `/var/lib/myapp/`.

At my end, I have updated my rpm installer to copy the ets files during `%post`. That was my mistake. So my application is sorted. However,

* It does look like an unexpected misbehaviour that it connects to the network, ignoring autoupdate: disabled.
* The error msg is confusing - why am I getting a network error (nxdomain) at startup of an app when I've configured it to run offline? (ie: autoupdate disabled).

**Comment by lau** [comment]
If there is no ETS file available it tries to download one at startup. It is working as intended. Tzdata cannot work without any time zone data. But it would be helpful if there was a log message or error message when no ETS file is found at startup.

Autoupdate is to update the existing data. The configuration for autoupdate is about checking for new versions periodically. This is a different service from the one checking if any ets files exist at startup.

**Comment by martin-langhoff** [comment]
Granted, perhaps we read too much into the meaning of disabling autoupdate. :-)

**Comment by martin-langhoff** [comment]
However, "offline" installs do exist, however infrequent they may be... :-)

**Comment by lau** [comment]
Thank you for letting me know about you experience :) I definitely think errors messages should be helpful.

I recognize that "offline" installs exist, and they should be supported as well as possible. Updating time zone data for running systems that are not connected to the internet is something that I want to make easier at some point.
