### ISSUE TITLE
No EDT timezone in Tzdata.zone_list

### ISSUE THREAD

**Issue by b0oh** [lau/tzdata#3]
There's missing EDT timezone, but it could be found in [northamerica](/lau/tzdata/tree/master/source_data/northamerica) and [australasia](/lau/tzdata/tree/master/source_data/australasia).

**Comment by lau** [comment]
Hi. EDT is not a unique name for a time zone. For time zone name you would want to use a name with a slash in it. For instance "America/Nipigon"

**Comment by b0oh** [comment]
Probably it is a [Timex](/bitwalker/timex) issue, I am tried to parse date like this `"Mon, 02 Mar 2015 06:48:00 EDT"` and parsing is failing. Timex just checking zones from Tzdata.zone_list.
