### ISSUE TITLE
Argument error on update

### ISSUE THREAD

**Issue by bernardd** [lau/tzdata#30]
We've just started getting this crash when tzdata tries to do an update of its data:
```
  crasher:
    initial call: Elixir.Tzdata.ReleaseUpdater:init/1
    pid: <0.2305.0>
    registered_name: tzdata_release_updater
    exception exit: {
{badarg,[{erlang,hd,[[]],[]},
{'Elixir.Tzdata.DataLoader',content_length_from_headers,1,[{file,"lib/tzdata/data_loader.ex"},{line,29}]},{'Elixir.Tzdata.DataLoader',do_latest_file_size,1,[{file,"lib/tzdata/data_loader.ex"},{line,51}]},
{'Elixir.Tzdata.ReleaseUpdater','loaded_tzdata_matches_iana_file_size?',0,[{file,"lib/tzdata/release_updater.ex"},{line,48}]},
{'Elixir.Tzdata.ReleaseUpdater',poll_for_update,0,[{file,"lib/tzdata/release_updater.ex"},{line,36}]},
{'Elixir.Tzdata.ReleaseUpdater',handle_info,2,[{file,"lib/tzdata/release_updater.ex"},{line,17}]},
{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,601}]},
{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,667}]}]},
[{gen_server,terminate,7,[{file,"gen_server.erl"},{line,812}]},
{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
```

Best as I can tell, the HEAD data it's pulling no longer contains the Content-Length field. Indeed a quick test seems to bear this out:

```
$ curl --head https://www.iana.org/time-zones/repository/tzdata-latest.tar.gz
HTTP/1.1 200 OK
Date: Tue, 07 Mar 2017 00:30:29 GMT
X-Frame-Options: SAMEORIGIN
Content-Security-Policy: upgrade-insecure-requests
Last-Modified: Tue, 28 Feb 2017 21:18:44 GMT
Vary: Accept-Encoding
content-type: application/x-gzip
content-encoding: identity
Cache-Control: public, max-age=3600
Server: Apache
X-Cache-Host: www-varnish.iana.org
X-Cache-Hits: 1413
Accept-Ranges: bytes
Connection: keep-alive
Strict-Transport-Security: max-age=48211200
```

But of course I could be misreading the code.

Edit: We're running 0.5.10

**Comment by polymetis** [comment]
Yeah I landed here as well. Except 
~~~elixir
Tzdata.DataLoader.download_new
~~~
headers look like this

~~~elixir
[{"Date", "Tue, 07 Mar 2017 00:17:13 GMT"}, {"X-Frame-Options", "SAMEORIGIN"},
 {"Content-Security-Policy", "upgrade-insecure-requests"},
 {"Last-Modified", "Tue, 28 Feb 2017 21:18:44 GMT"},
 {"Vary", "Accept-Encoding"}, {"content-type", "application/x-gzip"},
 {"content-encoding", "identity"}, {"Cache-Control", "public, max-age=3600"},
 {"Server", "Apache"}, {"X-Cache-Host", "www-varnish.iana.org"},
 {"X-Cache-Hits", "20995"}, {"Accept-Ranges", "bytes"},
 {"Content-Length", "323983"}, {"Connection", "keep-alive"},
 {"Strict-Transport-Security", "max-age=48211200"}]
~~~

Which is list so :erlang.hd should work? Investigating further

**Comment by bernardd** [comment]
I don't think it's going through `download_new`. To check for updates it hits `latest_file_size` which calls `:hackney.head/4`. So it's not doing a full download, only a HEAD call:

```
iex(1)> :hackney.head("https://www.iana.org/time-zones/repository/tzdata-latest.tar.gz", [], "", [])
{:ok, 200,
 [{"Date", "Tue, 07 Mar 2017 00:50:07 GMT"}, {"X-Frame-Options", "SAMEORIGIN"},
  {"Content-Security-Policy", "upgrade-insecure-requests"},
  {"Last-Modified", "Tue, 28 Feb 2017 21:18:44 GMT"},
  {"Vary", "Accept-Encoding"}, {"content-type", "application/x-gzip"},
  {"content-encoding", "identity"}, {"Cache-Control", "public, max-age=3600"},
  {"Server", "Apache"}, {"X-Cache-Host", "www-varnish.iana.org"},
  {"X-Cache-Hits", "805"}, {"Accept-Ranges", "bytes"},
  {"Connection", "keep-alive"},
  {"Strict-Transport-Security", "max-age=48211200"}]}
```

**Comment by polymetis** [comment]
@bernardd Okay a little further debugging revealed a difference between 

~~~elixir
:hackney.get
:hackney.head
~~~

This version will work but is super junky but I didn't want to deep dive into hackney at the moment. (In the middle of merge with something else) But if you need to get unstuck it's there. 

https://github.com/polymetis/tzdata

In particular this

https://github.com/polymetis/tzdata/commit/431044b31a2196ae98baec17451b5562070bd8f2

**Comment by lau** [comment]
Thanks for the reports. It does indeed seem like they stopped returning a `Content-Length` header.

**Comment by lau** [comment]
It looks like the `Content-Length` headers are back. I've been making alternative functionality that downloads the file and looks at the size - this could be used as a backup in case `Content-Length` headers go missing again.

**Comment by bernardd** [comment]
Awesome, thanks. Whatever the correct behaviour if/when it goes missing is, I'm pretty sure crashing shouldn't be it :)

**Comment by Hermanverschooten** [comment]
I guess this error I received last night is related?
```
GenServer :tzdata_release_updater terminating
** (ArgumentError) argument error
    :erlang.hd([])
    (tzdata) lib/tzdata/data_loader.ex:29: Tzdata.DataLoader.content_length_from_headers/1
    (tzdata) lib/tzdata/data_loader.ex:51: Tzdata.DataLoader.do_latest_file_size/1
    (tzdata) lib/tzdata/release_updater.ex:48: Tzdata.ReleaseUpdater.loaded_tzdata_matches_iana_file_size?/0
    (tzdata) lib/tzdata/release_updater.ex:36: Tzdata.ReleaseUpdater.poll_for_update/0
    (tzdata) lib/tzdata/release_updater.ex:17: Tzdata.ReleaseUpdater.handle_info/2
    (stdlib) gen_server.erl:601: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:667: :gen_server.handle_msg/5
Last message: :check_if_time_to_update
```

**Comment by jbrowning** [comment]
It looks like the `Content-Length` headers have gone away again:

```
iex(2)> :hackney.head("https://www.iana.org/time-zones/repository/tzdata-latest.tar.gz", [], "", [])
{:ok, 200,
 [{"Date", "Tue, 07 Mar 2017 13:36:41 GMT"},
  {"Expires", "Tue, 07 Mar 2017 14:36:41 GMT"},
  {"Cache-Control", "max-age=3600"}, {"X-Frame-Options", "SAMEORIGIN"},
  {"Content-Security-Policy", "upgrade-insecure-requests"},
  {"Last-Modified", "Tue, 28 Feb 2017 21:18:44 GMT"},
  {"Vary", "Accept-Encoding"}, {"content-type", "application/x-gzip"},
  {"content-encoding", "identity"}, {"Server", "Apache"},
  {"X-Cache-Hits", "43539"}, {"Accept-Ranges", "bytes"},
  {"Connection", "keep-alive"},
  {"Strict-Transport-Security", "max-age=48211200"}]}
```

Maybe there's a misbehaving server in their pool.

**Comment by myronmarston** [comment]
Is there a work around for this?

**Comment by lau** [comment]
I hope to release a new version tonight that can get the file size without the headers.

**Comment by lau** [comment]
Version 0.5.11 has been released: https://hex.pm/packages/tzdata

```elixir
{:tzdata, "~> 0.5.11"}
```

Let me know if it works well for you.

**Comment by alex88** [comment]
Works perfectly here after the update

**Comment by bernardd** [comment]
Working here too. I'm going to close this. Thanks heaps for the quick response.

**Comment by slashmili** [comment]
@Iau time to time I still get the same error in our production

I'm using:
```
"tzdata": {:hex, :tzdata, "0.5.11", "3d5469a9f46bdf4a8760333dbdabdcc4751325035c454b10521f71e7c611ae50"
```

```
Erlang/OTP 19 [erts-8.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]

Interactive Elixir (1.4.1) - press Ctrl+C to exit (type h() ENTER for help)
```

and the stack trace is 
```
GenServer :tzdata_release_updater terminating
** (ArgumentError) argument error
    :erlang.hd([])
    (tzdata) lib/tzdata/data_loader.ex:29: Tzdata.DataLoader.content_length_from_headers/1
    (tzdata) lib/tzdata/data_loader.ex:51: Tzdata.DataLoader.do_latest_file_size/1
    (tzdata) lib/tzdata/release_updater.ex:48: Tzdata.ReleaseUpdater.loaded_tzdata_matches_iana_file_size?/0
    (tzdata) lib/tzdata/release_updater.ex:36: Tzdata.ReleaseUpdater.poll_for_update/0
    (tzdata) lib/tzdata/release_updater.ex:17: Tzdata.ReleaseUpdater.handle_info/2
    (stdlib) gen_server.erl:601: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:667: :gen_server.handle_msg/5
Last message: :check_if_time_to_update
```

**Comment by bernardd** [comment]
> I'm using:
> `"tzdata": {:hex, :tzdata, "0.5.11", "3d5469a9f46bdf4a8760333dbdabdcc4751325035c454b10521f71e7c611ae50"`

No you're not :) Because

> `lib/tzdata/data_loader.ex:29: Tzdata.DataLoader.content_length_from_headers/1`

Line 29 in v0.5.11 is not a call to `hd` any more, but it was in 0.5.10. Have you actually pushed out the new version to your production system and/or reloaded it?

**Comment by slashmili** [comment]
@bernardd good point! thanks I'll take a look

**Comment by Ljzn** [comment]
> [error] GenServer :tzdata_release_updater terminating
> ** (MatchError) no match of right hand side value: {:error, :timeout}
>     (tzdata) lib/tzdata/data_loader.ex:52: Tzdata.DataLoader.latest_file_size_by_get/1
>     (tzdata) lib/tzdata/release_updater.ex:48: Tzdata.ReleaseUpdater.loaded_tzdata_matches_iana_file_size?/0
>     (tzdata) lib/tzdata/release_updater.ex:36: Tzdata.ReleaseUpdater.poll_for_update/0
>     (tzdata) lib/tzdata/release_updater.ex:17: Tzdata.ReleaseUpdater.handle_info/2
>     (stdlib) gen_server.erl:601: :gen_server.try_dispatch/4
>     (stdlib) gen_server.erl:667: :gen_server.handle_msg/5
>     (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
> Last message: :check_if_time_to_update
> State: []

hi, I am using tzdata 0.5.11. Does anyone know how to solve it?

**Comment by lau** [comment]
@Ljzn Try version 0.5.12. If you don't have internet access or if the IANA servers are unresponsive that could happen. By default it will try again the following day. If an error happens and it cannot check for new versions, the existing version of the data will be used until it successfully finds and downloads a new version.
