### ISSUE TITLE
data_loader.ex does not use If-Modified-Since

### ISSUE THREAD

**Issue by ptudor** [lau/tzdata#33]
Hi, 

I'm writing to suggest complementing or replacing the existing Content-Length checks in data_loader.ex with an [If-Modified-Since](https://tools.ietf.org/html/rfc7232#section-3.3) header, commonly used by web browsers to avoid the delay of a download operation.

````bash
% nc -C www.iana.org 80
GET /time-zones/repository/tzdata-latest.tar.gz HTTP/1.1
Host: www.iana.org
User-Agent: https://github.com/lau/tzdata
If-Modified-Since: Tue, 28 Feb 2017 21:18:44 GMT

HTTP/1.1 304 Not Modified
Date: Thu, 09 Mar 2017 04:33:21 GMT
Last-Modified: Tue, 28 Feb 2017 21:18:44 GMT
````

I would like to have attached a patch, but I'm not familiar enough with Erlang/Hackney to quickly create one to use this If-Modified-Since method. However, I'm interested enough in seeing this feature exist I'd hack up a diff after a day's research if that's what I have to do.

I hope this suggestion can perhaps simplify the operation: Instead of a combination of GETs and HEADs the fetch could become just GETs, with the difference between an unmodified GET or modified GET revealed by the empty 304 or normal 200 response.

Thanks,

**Comment by lau** [comment]
Hi. Thank you for the suggestion. I'm planning to implement a solution that uses the Last-Modified headers. The solution in 0.5.11 is a stop gap solution that was caused by IANA serving the files differently. Look out for a 0.5.12 release :)

**Comment by lau** [comment]
0.5.12 released
