### ISSUE TITLE
Negative leap seconds

### ISSUE THREAD

**Issue by alvinlindstam** [lau/tzdata#39]
This might be more theoretical than practical, but as I understand it there could be negative leap seconds (that is, a second less than normal) and not just extra leap seconds. It's never happened so far, but the UTC standard seems to be built upon than possibility.

How would tzdata handle a negative leap second? [`leap_seconds/0`](https://hexdocs.pm/tzdata/Tzdata.html#leap_seconds/0) only states when a leap second occurs, assuming (explicitly in the function documentation) that it's extra (positive) leap seconds.

**Comment by lau** [comment]
Short answer: It does would handle negative leap seconds well. They haven't happened yet. No signs of it happening soon. Perhaps the docs could be improved to explain this.

**Comment by alvinlindstam** [comment]
Yes, some documentation adjustment could be nice. For instance, would a negative leap second have the datetime of the last occuring second (`{23, 59, 58}`) or the skipped second (`{23, 59, 59}`)
