### ISSUE TITLE
compile issue

### ISSUE THREAD

**Issue by jschoch** [lau/tzdata#4]
==> tzdata
Compiled lib/tzdata/parser_organizer.ex
Compiled lib/tzdata/release_parser.ex
Compiled lib/tzdata/util.ex
Compiled lib/tzdata/table_parser.ex
Compiled lib/tzdata/parser.ex
Compiled lib/tzdata/table_data.ex
Compiled lib/tzdata/leap_sec_parser.ex
Compiled lib/tzdata/basic_data.ex
Compiled lib/tzdata/period_builder.ex
Compiled lib/tzdata/far_future_dynamic_periods.ex
*** stack smashing detected ***: /usr/local/lib/erlang/erts-6.2/bin/beam terminated
Segmentation fault (core dumped)

**Comment by lau** [comment]
This is a known issue that comes up when compiling on machines with less than 2GB of memory.

I am working on a new structure for Tzdata, which should get rid of that problem. But for now the only solution I have is to use a machine with at least 2GB of RAM.

On what kind of machine are you getting that problem?

**Comment by jschoch** [comment]
An obvious solution to this is to turn on enough swap so it can compile, though slower.

**Comment by lau** [comment]
FYI: The new version (0.5.1) is out.
