### ISSUE TITLE
Argument error in Tzdata.ReleaseReader

### ISSUE THREAD

**Issue by bitwalker** [lau/tzdata#5]
Hey @lau, was updating Timex's tzdata dependency to 0.5.1 and hit the following error when calling `Tzdata.canonical_zone_list`:

```
Erlang/OTP 18 [erts-7.0.2] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Interactive Elixir (1.0.5) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> Tzdata.canonical_zone_list
** (ArgumentError) argument error
    (stdlib) :ets.lookup(:tzdata_current_release, :release_version)
    (tzdata) lib/tzdata/release_reader.ex:41: Tzdata.ReleaseReader.current_release_from_table/0
    (tzdata) lib/tzdata/release_reader.ex:13: Tzdata.ReleaseReader.simple_lookup/1
    (tzdata) lib/tzdata/release_reader.ex:5: Tzdata.ReleaseReader.zone_list/0
iex(1)>
```

**Comment by lau** [comment]
Hi @bitwalker Did you put :tzdata in the applications list?

**Comment by bitwalker** [comment]
Ah I still had it just in `:included_applications`. Sorry about that!

**Comment by lau** [comment]
No worries. Also keep in mind that users of Timex will have to have their app start Tzdata if it is ~> 0.5.1. For instance
by adding :tzdata to the applications: list in their mix.exs file. This is not required for ~> 0.1.7, but it won't hurt to add it.

That's why I added this to the Calendar readme. Maybe you want to add that (or something similar) too:

--

Also add `tzdata` to the list of applications in the mix.exs file:

```elixir
  def application do
    [applications: [:logger, :tzdata]]
  end
```

**Comment by nathany** [comment]
Thanks @lau. I made the same mistake too.

**Comment by thisismydesign** [comment]
Hey,

I'm getting the same error when trying to use `Tzdata 0.5.12` (e.g. `Tzdata.canonical_zone_list`) in a module attribute. It is present in the applications list. Taken from the [getting started guide](https://elixir-lang.org/getting-started/module-attributes.html#as-constants): 

> Any functions may be called when defining a module attribute.

Any idea what the issue might be?

**Comment by lau** [comment]
Hi @thisismydesign 
Please update to the newest version of Tzdata (currently `0.5.16`).
Which version of Elixir are you using? Tzdata needs to be started somehow. In certain versions of Elixir Tzdata (or a library using it, such as Calendar), needs to be in the `applications` list.

**Comment by thisismydesign** [comment]
@lau thanks for the quick reply!

I'm using Tzdata  natively and it's already in the applications list.

Elixir version:
```
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.4.5
```

**Comment by thisismydesign** [comment]
My usage is like this:

```elixir
defmodule Module do
  @timezones Tzdata.canonical_zone_list
```

**Comment by alfonsoperez** [comment]
I am also getting the same, with a different call.

I have this piece of code:
```
    case Timex.Timezone.get(data) do
      {:error, _} = error ->
        error

      data ->
        {:ok, data}
    end
```

to put timezones that are saved in the database into a struct.

Well when running a migration that gets some data through an Ecto Query I get this error:

```
** (ArgumentError) argument error
    (stdlib) :ets.lookup(:tzdata_current_release, :release_version)
    lib/tzdata/release_reader.ex:47: Tzdata.ReleaseReader.current_release_from_table/0
    lib/tzdata/release_reader.ex:14: Tzdata.ReleaseReader.simple_lookup/1
    lib/tzdata/release_reader.ex:7: Tzdata.ReleaseReader.zone_and_link_list/0
    lib/tzdata.ex:40: Tzdata.zone_exists?/1
    lib/timezone/timezone.ex:152: Timex.Timezone.name_of/1
    lib/timezone/timezone.ex:180: Timex.Timezone.get/2
    lib/common/ecto/timezone.ex:27: Common.Ecto.Timezone.load/1
    (ecto) lib/ecto/type.ex:661: Ecto.Type.process_loaders/3
    (ecto) lib/ecto/schema.ex:1490: Ecto.Schema.load!/5
    (ecto) lib/ecto/schema.ex:1442: Ecto.Schema.safe_load_zip/4
    (ecto) lib/ecto/schema.ex:1443: Ecto.Schema.safe_load_zip/4
    (ecto) lib/ecto/schema.ex:1430: Ecto.Schema.__safe_load__/6
    (ecto) lib/ecto/repo/queryable.ex:282: Ecto.Repo.Queryable.process_source/6
    (ecto) lib/ecto/repo/queryable.ex:170: Ecto.Repo.Queryable.preprocess/5
    (postgrex) lib/postgrex/query.ex:77: DBConnection.Query.Postgrex.Query.decode_map/3
    (postgrex) lib/postgrex/query.ex:64: DBConnection.Query.Postgrex.Query.decode/3
    (db_connection) lib/db_connection.ex:1019: DBConnection.decode/6
    (ecto) lib/ecto/adapters/postgres/connection.ex:73: Ecto.Adapters.Postgres.Connection.prepare_execute/5
    (ecto) lib/ecto/adapters/sql.ex:256: Ecto.Adapters.SQL.sql_call/6
```


Which has that code in the stack trace and doing some Inspects can verify that that's indeed the call that triggers the error, although doing:

```
iex(1)> Timex.Timezone.get("America/Los_Angeles")
#<TimezoneInfo(America/Los_Angeles - PDT (-07:00:00))>
```

What's interesting is that if I run the same code `iex -S mix` works.

**Comment by bitwalker** [comment]
You need to execute `Application.ensure_all_started(:timex)` in your migrations, the problem is that the `:tzdata` application is not running, and so that ETS table is missing. This doesn't happen when you run `iex -S mix` because Mix is starting `:tzdata`

**Comment by alfonsoperez** [comment]
Makes sense @bitwalker, thanks!
