### ISSUE TITLE
TZ updates with read only file system

### ISSUE THREAD

**Issue by tomciopp** [lau/tzdata#55]
In production we use a read only file system which causes problems when trying to update tzdata. We are running into an infinite loop where the system tries to update => write a file => crash => recover from crash => update. I know that there is an option to turn off auto updating (which we have since done) but I was wondering if there was a better way to engineer updates to the tz info. 

Here are two proposals that I think would work:
Based on historical data, it looks like there are only around 9-10 changes to the tz database per year[0]. We could just automate the process of downloading the file and commiting a PR which would also bump the patch level of the library. This would allow people who can't auto update to get the most recent info.

Or

Change the auto update process to not rely on files. I think we should be able to hold everything in memory based on my quick overview of the update process. We lose the benefit of being able to read a cache from disk but I don't really think this is a show stopper in terms of perf since this is an async action anyway.

0: [ftp://ftp.iana.org/tz/releases](ftp://ftp.iana.org/tz/releases/)

**Comment by lau** [comment]
Hi. A new version has just been released (0.5.15). See the updated README. If you have a read only file system you can put an .ets file with the newest data available in the configured `data_dir`.

Yes it would be possible to use auto update via the internet and not save the new data to file. That could potentially be added as a config option. However it would mean that the if Tzdata restarts it would go back to the old version on the read only file system. Potentially going back and forth between an old and new version.

May I ask what sort of application is it that is connected to the internet but has no writeable disk space?

**Comment by tomciopp** [comment]
The application handles electronic medical records. It is shipped in a docker container with no access to a mounted disk. This allows us to avoid a series of attack vectors that most normal web apps don't consider protecting against. A package arbitrarily writing files is just something we can't condone. It can only write to a database that is not connected to the public internet.

**Comment by lau** [comment]
One problem with getting updates and not writing to disk is that upon restarts it would go back to an old version from disk. So you could cycle back and forth between old and new versions. If you don't want the library to write to disk you could write your own code that puts `.ets` files in a location you specify in the config and then trigger loading of the new database from that file.
