### ISSUE TITLE
Issue with tzdata 

### ISSUE THREAD

**Issue by ijunaid8989** [lau/tzdata#66]
```elixir
iex(6)> {:ok, mvd } = Calendar.DateTime.from_erl {{2014,10,4},{23,44,32}}, "Etc/UTC"
{:ok, #DateTime<2014-10-04 23:44:32Z>}
iex(7)> mvd |> Calendar.DateTime.shift_zone!("Europe/London")
#DateTime<2014-10-05 00:44:32+01:00 BST Europe/London>
iex(8)> mvd |> Calendar.DateTime.shift_zone!("Europe/Dublin")
#DateTime<2014-10-04 23:44:32+00:00 GMT Europe/Dublin>
iex(9)> 
```
There is some issue in changing timezone when its Dublin, there is one hour difference between UTC and Dublin time but conversion is not adding day light saving.

Can you guide?

**Comment by lau** [comment]
Hi @ijunaid8989 

As noted in the Calendar repo issue there was indeed a problem. Please upgrade to tzdata 0.5.19

Thank you
