### ISSUE TITLE
Unexpected results using Tzdata.TimeZoneDatabase and DateTime.shift_zone

### ISSUE THREAD

**Issue by bismark** [lau/tzdata#76]
This happens on the summer/winter time change boundary:

```
iex(57)> datetimes = [datetime1, datetime2, datetime3]
[#DateTime<2018-10-28 00:59:59Z>, #DateTime<2018-10-28 01:00:00Z>,
 #DateTime<2018-10-28 01:00:01Z>]
iex(58)> Enum.map(datetimes, &DateTime.shift_zone(&1, "Europe/Copenhagen"))
[
  ok: #DateTime<2018-10-28 02:59:59+02:00 CEST Europe/Copenhagen>,
  error: :time_zone_not_found,
  ok: #DateTime<2018-10-28 02:00:01+01:00 CET Europe/Copenhagen>
]
```

I *think* I should expect `#DateTime<2018-10-28 02:00:00+01:00 CET Europe/Copenhagen>` for the second element.

I'm guessing it's due to this line: https://github.com/lau/tzdata/blob/b556189f1d0ad4aa25425c9f415427afa8d371cb/lib/tzdata/time_zone_database.ex#L17

**Comment by bismark** [comment]
For reference moment.js handles this as follows:

```
> moment('2018-10-28T01:00:00Z').tz("Europe/Copenhagen").format()
'2018-10-28T02:00:00+01:00'
```

**Comment by bismark** [comment]
Looks like this bug was introduced in #75, pinning to `186b259c990562cd946e985e6b73c8352cdb283a` for now solves my issue.

**Comment by lau** [comment]
Hi @bismark 

Thank you for reporting that. I think I have found the issue. I will keep you posted.

**Comment by lau** [comment]
@bismark I have pushed an update to master: 
a77a2a564a61df39d5b405086c4e2b822f72db4b
