### ISSUE TITLE
Question: why were the functions related to `zone1970.tab` data removed (module `TableData`)?

### ISSUE THREAD

**Issue by mathieuprog** [lau/tzdata#95]
I found some useful functions using the `zone1970.tab` data, that allow for example to retrieve the timezone names based on a country code. This seems useful for example for helping a user to pick a timezone based on a country input.

The module providing such functions (`TableData`) was found in the 0.1.x versions but has since then been removed.
https://github.com/lau/tzdata/commit/69081f36bce05adb6d3ff78012f42cba6eafec61
https://github.com/lau/tzdata/commit/07efc3ec4c101e175e6416bfac2757f66d0a181b

I was just curious to know why this has been removed.

**Comment by mathieuprog** [comment]
I have extracted the data myself from iso3166.tab and zone1970.tab, so no longer an issue.

**Comment by lleger** [comment]
@mathieuprog Any chance you can share the code you wrote? I have the same use case you mentioned and it'd be great to list out the timezones per country. Thanks!

**Comment by mathieuprog** [comment]
@lleger you can find the repo here: https://github.com/mathieuprog/tz_extra, and you can find usage in readme file. Note however that it depends on `tz`: https://github.com/mathieuprog/tz, an alternative to `tzdata`.

**Comment by lleger** [comment]
That's awesome @mathieuprog, thank you! 🍻
